#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_dir=$(cd -- "${script_dir}/.." && pwd)
inventory_path=${ANSIBLE_INVENTORY:-${repo_dir}/.local/ansible-inventory.json}
node_name=${1:-}
remote_command=${2:-}

test -n "${node_name}" && test -n "${remote_command}" || {
  echo "usage: $0 NODE 'REMOTE COMMAND'" >&2
  exit 2
}
command -v jq >/dev/null
command -v ssh >/dev/null
test -f "${inventory_path}" || { echo "run make discover first" >&2; exit 1; }

node=$(jq -ce --arg name "${node_name}" '
  .all as $all |
  [$all.children[].hosts | to_entries[] | select(.key == $name) |
    .value + {name: .key, default_user: $all.vars.ansible_user,
      identity_file: $all.vars.ansible_ssh_private_key_file,
      common_args: $all.vars.ansible_ssh_common_args}] | first
' "${inventory_path}") || {
  echo "unknown node: ${node_name}" >&2
  exit 1
}

host=$(jq -r '.ansible_host' <<<"${node}")
user=$(jq -r '.ansible_user // .default_user' <<<"${node}")
identity_file=$(jq -r '.identity_file' <<<"${node}")
common_args=$(jq -r '.common_args' <<<"${node}")
case "${identity_file}" in /*) ;; *) identity_file=${repo_dir}/${identity_file} ;; esac
test -f "${identity_file}" || { echo "missing SSH identity: ${identity_file}" >&2; exit 1; }

# common_args is generated by this repository, not accepted from benchmark output.
# shellcheck disable=SC2206
ssh_options=(${common_args})
exec ssh -i "${identity_file}" "${ssh_options[@]}" "${user}@${host}" "${remote_command}"
